-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Quiz.Object exposing (..)


type Choices
    = Choices


type Game
    = Game


type GameFinished
    = GameFinished


type GameStarted
    = GameStarted


type KVStringString
    = KVStringString


type LeaderboardEntry
    = LeaderboardEntry


type NextQuestion
    = NextQuestion


type PlayerCodeCreated
    = PlayerCodeCreated


type PlayerJoined
    = PlayerJoined


type Question
    = Question


type QuestionEnded
    = QuestionEnded


type QuestionWithSolution
    = QuestionWithSolution


type Quiz
    = Quiz


type QuizEntity
    = QuizEntity
