-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Quiz.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Quiz.Scalar exposing (defaultCodecs)


type alias Long =
    Quiz.Scalar.Long


type alias Unit =
    Quiz.Scalar.Unit


codecs : Quiz.Scalar.Codecs Long Unit
codecs =
    Quiz.Scalar.defineCodecs
        { codecLong = defaultCodecs.codecLong
        , codecUnit = defaultCodecs.codecUnit
        }
