-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Quiz.Object.Game exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Quiz.InputObject
import Quiz.Interface
import Quiz.Object
import Quiz.Scalar
import Quiz.ScalarCodecs
import Quiz.Union


gameId : SelectionSet String Quiz.Object.Game
gameId =
    Object.selectionForField "String" "gameId" [] Decode.string


title : SelectionSet String Quiz.Object.Game
title =
    Object.selectionForField "String" "title" [] Decode.string


pin : SelectionSet String Quiz.Object.Game
pin =
    Object.selectionForField "String" "pin" [] Decode.string


adminCode : SelectionSet String Quiz.Object.Game
adminCode =
    Object.selectionForField "String" "adminCode" [] Decode.string


quizEntity :
    SelectionSet decodesTo Quiz.Object.QuizEntity
    -> SelectionSet decodesTo Quiz.Object.Game
quizEntity object____ =
    Object.selectionForCompositeField "quizEntity" [] object____ identity


createdTimestamp : SelectionSet Quiz.ScalarCodecs.Long Quiz.Object.Game
createdTimestamp =
    Object.selectionForField "ScalarCodecs.Long" "createdTimestamp" [] (Quiz.ScalarCodecs.codecs |> Quiz.Scalar.unwrapCodecs |> .codecLong |> .decoder)
