-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Quiz.Object.PlayerCodeCreated exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Quiz.InputObject
import Quiz.Interface
import Quiz.Object
import Quiz.Scalar
import Quiz.ScalarCodecs
import Quiz.Union


playerId : SelectionSet String Quiz.Object.PlayerCodeCreated
playerId =
    Object.selectionForField "String" "playerId" [] Decode.string


playerCode : SelectionSet String Quiz.Object.PlayerCodeCreated
playerCode =
    Object.selectionForField "String" "playerCode" [] Decode.string


gameId : SelectionSet String Quiz.Object.PlayerCodeCreated
gameId =
    Object.selectionForField "String" "gameId" [] Decode.string
